import { PlayerModel } from "../models/player-model";
import { StatisticsModel } from "../models/statistics-model";

const database: PlayerModel[] = [
  {
    id: 1,
    name: "Neymar",
    club: "Barcelona",
    nacionality: "Brasileiro",
    position: "Atacante",
    age: 28,
    statistics: {
      overall: 90,
      pace: 94,
      shooting: 92,
      passing: 88,
      dribbling: 95,
      defending: 40,
      psysical: 75,
    },
  },
  {
    id: 2,
    name: "Lionel Messi",
    club: "Barcelona",
    nacionality: "Argentino",
    position: "Atacante",
    age: 33,
    statistics: {
      overall: 93,
      pace: 87,
      shooting: 92,
      passing: 91,
      dribbling: 96,
      defending: 32,
      psysical: 65,
    },
  },
  {
    id: 3,
    name: "Gerard Piqué",
    club: "Barcelona",
    nacionality: "Espanhol",
    position: "Defensor",
    age: 34,
    statistics: {
      overall: 86,
      pace: 68,
      shooting: 60,
      passing: 77,
      dribbling: 62,
      defending: 88,
      psysical: 80,
    },
  },
  {
    id: 4,
    name: "Sergio Busquets",
    club: "Barcelona",
    nacionality: "Espanhol",
    position: "Meio-campo",
    age: 32,
    statistics: {
      overall: 87,
      pace: 60,
      shooting: 65,
      passing: 80,
      dribbling: 79,
      defending: 85,
      psysical: 77,
    },
  },
  {
    id: 5,
    name: "Marc-André ter Stegen",
    club: "Barcelona",
    nacionality: "Alemão",
    position: "Goleiro",
    age: 28,
    statistics: {
      overall: 90,
      pace: 50,
      shooting: 30,
      passing: 85,
      dribbling: 30,
      defending: 15,
      psysical: 75,
    },
  },
  {
    id: 6,
    name: "Karim Benzema",
    club: "Real Madrid",
    nacionality: "Francês",
    position: "Atacante",
    age: 32,
    statistics: {
      overall: 89,
      pace: 77,
      shooting: 84,
      passing: 82,
      dribbling: 88,
      defending: 40,
      psysical: 74,
    },
  },
  {
    id: 7,
    name: "Sergio Ramos",
    club: "Real Madrid",
    nacionality: "Espanhol",
    position: "Defensor",
    age: 34,
    statistics: {
      overall: 89,
      pace: 75,
      shooting: 65,
      passing: 76,
      dribbling: 72,
      defending: 90,
      psysical: 83,
    },
  },
  {
    id: 8,
    name: "Luka Modric",
    club: "Real Madrid",
    nacionality: "Croata",
    position: "Meio-campo",
    age: 35,
    statistics: {
      overall: 87,
      pace: 74,
      shooting: 75,
      passing: 89,
      dribbling: 90,
      defending: 66,
      psysical: 70,
    },
  },
  {
    id: 9,
    name: "Thibaut Courtois",
    club: "Real Madrid",
    nacionality: "Belga",
    position: "Goleiro",
    age: 28,
    statistics: {
      overall: 88,
      pace: 50,
      shooting: 30,
      passing: 70,
      dribbling: 35,
      defending: 20,
      psysical: 80,
    },
  },
  {
    id: 10,
    name: "Eden Hazard",
    club: "Real Madrid",
    nacionality: "Belga",
    position: "Atacante",
    age: 29,
    statistics: {
      overall: 88,
      pace: 89,
      shooting: 82,
      passing: 84,
      dribbling: 92,
      defending: 35,
      psysical: 65,
    },
  },
  {
    id: 11,
    name: "Kylian Mbappé",
    club: "Paris Saint-Germain",
    nacionality: "Francês",
    position: "Atacante",
    age: 22,
    statistics: {
      overall: 91,
      pace: 96,
      shooting: 86,
      passing: 78,
      dribbling: 92,
      defending: 39,
      psysical: 76,
    },
  },
  {
    id: 12,
    name: "Marco Verratti",
    club: "Paris Saint-Germain",
    nacionality: "Italiano",
    position: "Meio-campo",
    age: 28,
    statistics: {
      overall: 86,
      pace: 70,
      shooting: 65,
      passing: 88,
      dribbling: 89,
      defending: 80,
      psysical: 67,
    },
  },
  {
    id: 13,
    name: "Marquinhos",
    club: "Paris Saint-Germain",
    nacionality: "Brasileiro",
    position: "Defensor",
    age: 26,
    statistics: {
      overall: 87,
      pace: 74,
      shooting: 60,
      passing: 78,
      dribbling: 75,
      defending: 88,
      psysical: 82,
    },
  },
  {
    id: 14,
    name: "Keylor Navas",
    club: "Paris Saint-Germain",
    nacionality: "Costarriquenho",
    position: "Goleiro",
    age: 33,
    statistics: {
      overall: 87,
      pace: 52,
      shooting: 30,
      passing: 70,
      dribbling: 40,
      defending: 15,
      psysical: 75,
    },
  },
  {
    id: 15,
    name: "Ángel Di María",
    club: "Paris Saint-Germain",
    nacionality: "Argentino",
    position: "Atacante",
    age: 32,
    statistics: {
      overall: 87,
      pace: 86,
      shooting: 80,
      passing: 85,
      dribbling: 88,
      defending: 55,
      psysical: 68,
    },
  },
  {
    id: 16,
    name: "Cristiano Ronaldo",
    club: "Juventus",
    nacionality: "Português",
    position: "Atacante",
    age: 35,
    statistics: {
      overall: 92,
      pace: 89,
      shooting: 93,
      passing: 81,
      dribbling: 88,
      defending: 35,
      psysical: 78,
    },
  },
  {
    id: 17,
    name: "Paulo Dybala",
    club: "Juventus",
    nacionality: "Argentino",
    position: "Atacante",
    age: 27,
    statistics: {
      overall: 87,
      pace: 85,
      shooting: 81,
      passing: 84,
      dribbling: 91,
      defending: 40,
      psysical: 63,
    },
  },
  {
    id: 18,
    name: "Giorgio Chiellini",
    club: "Juventus",
    nacionality: "Italiano",
    position: "Defensor",
    age: 36,
    statistics: {
      overall: 86,
      pace: 67,
      shooting: 45,
      passing: 60,
      dribbling: 55,
      defending: 90,
      psysical: 82,
    },
  },
  {
    id: 19,
    name: "Leonardo Bonucci",
    club: "Juventus",
    nacionality: "Italiano",
    position: "Defensor",
    age: 33,
    statistics: {
      overall: 85,
      pace: 65,
      shooting: 55,
      passing: 78,
      dribbling: 60,
      defending: 87,
      psysical: 78,
    },
  },
  {
    id: 20,
    name: "Wojciech Szczesny",
    club: "Juventus",
    nacionality: "Polonês",
    position: "Goleiro",
    age: 30,
    statistics: {
      overall: 87,
      pace: 60,
      shooting: 30,
      passing: 70,
      dribbling: 40,
      defending: 10,
      psysical: 80,
    },
  },
  {
    id: 21,
    name: "Robert Lewandowski",
    club: "Bayern Munich",
    nacionality: "Polonês",
    position: "Atacante",
    age: 32,
    statistics: {
      overall: 91,
      pace: 78,
      shooting: 92,
      passing: 77,
      dribbling: 85,
      defending: 43,
      psysical: 82,
    },
  },
  {
    id: 22,
    name: "Manuel Neuer",
    club: "Bayern Munich",
    nacionality: "Alemão",
    position: "Goleiro",
    age: 34,
    statistics: {
      overall: 90,
      pace: 50,
      shooting: 30,
      passing: 75,
      dribbling: 35,
      defending: 20,
      psysical: 80,
    },
  },
  {
    id: 23,
    name: "Joshua Kimmich",
    club: "Bayern Munich",
    nacionality: "Alemão",
    position: "Meio-campo",
    age: 25,
    statistics: {
      overall: 88,
      pace: 75,
      shooting: 70,
      passing: 87,
      dribbling: 84,
      defending: 85,
      psysical: 77,
    },
  },
  {
    id: 24,
    name: "Thomas Müller",
    club: "Bayern Munich",
    nacionality: "Alemão",
    position: "Atacante",
    age: 31,
    statistics: {
      overall: 86,
      pace: 70,
      shooting: 82,
      passing: 81,
      dribbling: 80,
      defending: 60,
      psysical: 74,
    },
  },
  {
    id: 25,
    name: "Leon Goretzka",
    club: "Bayern Munich",
    nacionality: "Alemão",
    position: "Meio-campo",
    age: 26,
    statistics: {
      overall: 84,
      pace: 74,
      shooting: 78,
      passing: 79,
      dribbling: 81,
      defending: 77,
      psysical: 82,
    },
  },
  {
    id: 26,
    name: "Kevin De Bruyne",
    club: "Manchester City",
    nacionality: "Belga",
    position: "Meio-campo",
    age: 29,
    statistics: {
      overall: 91,
      pace: 76,
      shooting: 86,
      passing: 93,
      dribbling: 88,
      defending: 60,
      psysical: 78,
    },
  },
  {
    id: 27,
    name: "Raheem Sterling",
    club: "Manchester City",
    nacionality: "Inglês",
    position: "Atacante",
    age: 26,
    statistics: {
      overall: 88,
      pace: 93,
      shooting: 81,
      passing: 78,
      dribbling: 89,
      defending: 45,
      psysical: 62,
    },
  },
  {
    id: 28,
    name: "Ruben Dias",
    club: "Manchester City",
    nacionality: "Português",
    position: "Defensor",
    age: 23,
    statistics: {
      overall: 87,
      pace: 73,
      shooting: 40,
      passing: 72,
      dribbling: 65,
      defending: 89,
      psysical: 83,
    },
  },
  {
    id: 29,
    name: "Ederson",
    club: "Manchester City",
    nacionality: "Brasileiro",
    position: "Goleiro",
    age: 27,
    statistics: {
      overall: 88,
      pace: 55,
      shooting: 40,
      passing: 91,
      dribbling: 70,
      defending: 15,
      psysical: 78,
    },
  },
  {
    id: 30,
    name: "Ilkay Gündogan",
    club: "Manchester City",
    nacionality: "Alemão",
    position: "Meio-campo",
    age: 30,
    statistics: {
      overall: 85,
      pace: 70,
      shooting: 77,
      passing: 85,
      dribbling: 82,
      defending: 75,
      psysical: 72,
    },
  },
];

export const findAllPlayers = async (): Promise<PlayerModel[]> => {
  return database;
};

export const findPlayerById = async (
  id: number
): Promise<PlayerModel | undefined> => {
  const findPlayer = database.find((player) => player.id === id);
  return findPlayer;
};

export const insertPlayer = async (player: PlayerModel) => {
  database.push(player);
};

export const deletePlayerById = async (id: number) => {
  const index = database.findIndex((player) => player.id === id);

  if (index !== -1) {
    database.splice(index, 1);
    return true;
  }
  return false;
};

export const findAndModifyPlayer = async (
  id: number,
  statistics: StatisticsModel
) => {
  // Encontra o player por id
  const playerIndex = database.findIndex((player) => player.id === id);
  if (playerIndex !== -1) {
    // Modifica o database
    database[playerIndex].statistics = statistics;
  }
  return database[playerIndex];
};
